export enum constantTag {
  constant_Class,
  constant_Fieldref,
  constant_Methodref,
  constant_InterfaceMethodref,
  constant_String,
  constant_Integer,
  constant_Float,
  constant_Long,
  constant_Double,
  constant_NameAndType,
  constant_Utf8,
  constant_MethodHandle,
  constant_MethodType,
  constant_InvokeDynamic,
}

export const constantTagMap: { [key: string]: constantTag } = {
  '7': constantTag.constant_Class,
  '9': constantTag.constant_Fieldref,
  '10': constantTag.constant_Methodref,
  '11': constantTag.constant_InterfaceMethodref,
  '8': constantTag.constant_String,
  '3': constantTag.constant_Integer,
  '4': constantTag.constant_Float,
  '5': constantTag.constant_Long,
  '6': constantTag.constant_Double,
  '12': constantTag.constant_NameAndType,
  '1': constantTag.constant_Utf8,
  '15': constantTag.constant_MethodHandle,
  '16': constantTag.constant_MethodType,
  '18': constantTag.constant_InvokeDynamic,
};
